language: bash
services: docker

env:
  - VERSION=4.0
  - VERSION=4.2
  - VERSION=4.4

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="request-tracker:$VERSION"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
